---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-app
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
        - name: covid-app
          imagePullPolicy: Always
          image: heissenberg/covid-app
          ports:
            - containerPort: 80