---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-app
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
        - name: covid-app
          imagePullPolicy: Always
          image: heissenberg/covid-app
          ports:
            - name: http
              containerPort: 9090
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m
          readinessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 2
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: "/etc/config.yaml"
      volumes:
        - name: config
          configMap:
            name: config